# Test configuration for maize

# Various options
scratch = "/tmp"
packages = [
    "maize.steps.mai"
]

# Default batch system options
[batch]
system = "local"
walltime = "24:00:00"

# Step-specific settings
[vina]
commands.vina = "./autodock_vina_1_1_2_linux_x86/bin/vina"

[vinascore]
commands.vina = "./autodock_vina_1_1_2_linux_x86/bin/vina"

[autodockgpu]
python = "/home/adi_sahasranamam/miniconda3/envs/maize-dev/bin/python"
modules = ["CUDA", "GCC"]
commands.autodock_gpu = "/home/adi_sahasranamam/REINVENT4/adgpu-v1.6_linux_x64_cuda12_128wi"

[gypsum]
scripts.gypsum.interpreter = "home/adi_sahasranamam/miniconda3/envs/gypsum_dl_env/bin/conda run -n gypsum_dl_env python"
scripts.gypsum.location = "home/adi_sahasranamam/miniconda3/envs/gypsum_dl_env/bin/run-gypsum-dl"

[reinvent]
scripts.reinvent.interpreter = "/home/adi_sahasranamam/miniconda3/envs/reinvent4/bin/python"
scripts.reinvent.location = "/home/adi_sahasranamam/miniconda3/envs/reinvent4/bin/reinvent"
